image: julia:1.5

before_script:  
  - apt-get install git-annex

default:
    script:
    - julia --project=@. -e "import Pkg; Pkg.test(; coverage = true)"
    - julia --project=test/coverage -e 'import Pkg; Pkg.instantiate()'
    - julia --project=test/coverage test/coverage/coverage-summary.jl
    artifacts:
        paths:
            - coverage/

    tags:
        - docker
pages:
    stage: deploy
    dependencies: 
        - default
    script:
        - mv coverage/ public/
    artifacts:
        paths:
            - public
        expire_in: 30 days
    only:
        - master
